<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ch.ge.filjava.apptemplatebackend</groupId>
    <artifactId>filjava-app-template-backend</artifactId>
    <version>0.0.1</version>
    <packaging>pom</packaging>

    <modules>
        <module>core</module>
        <module>infra</module>
        <module>ui</module>
    </modules>

    <scm>
        <connection>scm:git:${git.repository.url}</connection>
        <developerConnection>scm:git:${git.repository.url}</developerConnection>
        <url>${git.repository.url}</url>
        <tag>HEAD</tag>
    </scm>

    <properties>
        <git.repository.url>${GIT_REPOSITORY_URL}</git.repository.url>
        <maven.compiler.release>25</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <junit.version>5.11.4</junit.version>
        <cucumber.version>7.20.1</cucumber.version>
        <spring.boot.version>4.1.0</spring.boot.version>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <cxf.version>4.2.3</cxf.version>
        <jib-maven-plugin.version>3.5.1</jib-maven-plugin.version>
        <jacoco.version>0.8.13</jacoco.version>
        <sonar-maven-plugin.version>5.5.0.6356</sonar-maven-plugin.version>
        <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
        <maven-surefire-plugin.version>3.5.6</maven-surefire-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-core</artifactId>
                <version>11.0.24</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-core</artifactId>
                <version>1.5.35</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.22.2</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jsr310</artifactId>
                <version>2.22.2</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-api</artifactId>
                <version>2.26.1</version>
            </dependency>
            <dependency>
                <groupId>tools.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>3.1.6</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.sonarsource.scanner.maven</groupId>
                    <artifactId>sonar-maven-plugin</artifactId>
                    <version>${sonar-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring.boot.version}</version>
                </plugin>
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>${jib-maven-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>${jib-maven-plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>com.google.cloud.tools</groupId>
                        <artifactId>jib-ownership-extension-maven</artifactId>
                        <version>0.1.0</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <ports>
                        <port>8080</port>
                    </ports>
                    <jvmFlags>
                        <jvmFlag>-Xms512m</jvmFlag>
                        <jvmFlag>-Xmx1024m</jvmFlag>
                        <jvmFlag>-Dspring.profiles.active=prod</jvmFlag>
                        <jvmFlag>-Dfile.encoding=UTF-8</jvmFlag>
                    </jvmFlags>
                    <from>
                        <image>${jib_image_from}</image>
                    </from>
                    <to>
                        <image>${jib_image_to}</image>
                        <tags>
                            <tag>latest</tag>
                            <tag>${jib_image_to_tag}</tag>
                        </tags>
                    </to>
                    <container>
                        <user>gva</user>
                        <mainClass>ch.ge.filjava.apptemplatebackend.ui.main.FiljavaApplication</mainClass>
                        <appRoot>${jib.container.appRoot}</appRoot>
                        <labels>
                            <org.opencontainers.image.title>Image de test ci-validation-container-full-ci-jib</org.opencontainers.image.title>
                            <org.opencontainers.image.version>${project.version}</org.opencontainers.image.version>
                            <org.opencontainers.image.description>Image de l'application ci-validation-container-full-ci-jib</org.opencontainers.image.description>
                            <org.opencontainers.image.source>${jib_image_from}</org.opencontainers.image.source>
                            <org.opencontainers.image.vendor>OCSIN</org.opencontainers.image.vendor>
                            <org.opencontainers.image.licenses>TO BE DEFINED</org.opencontainers.image.licenses>
                            <ch.ge.ocsin.image.application>TO BE DEFINED</ch.ge.ocsin.image.application>
                            <org.opencontainers.image.base.name>TO BE DEFINED</org.opencontainers.image.base.name>
                        </labels>
                    </container>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
