sonar.sources=core/src/main/java,infra/src/main/java,ui/src/main/java
sonar.java.binaries=core/target/classes,infra/target/classes,ui/target/classes
sonar.coverage.jacoco.xmlReportPaths=core/target/site/jacoco/jacoco.xml,infra/target/site/jacoco/jacoco.xml,ui/target/site/jacoco/jacoco.xml
